FROM python:3.11-slim

WORKDIR /app

# Устанавливаем совместимые версии
RUN pip install pymongo==4.6.1 motor==3.3.2 fastapi uvicorn cryptography python-jose python-dotenv

COPY . .

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]